### ISSUE TITLE
FCB Rename structure is not per DOS definition

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#34]
I tried to revert the change to the rfcb structure introduced in e8196ab6 and pack to match the DOS definition as per
```C
diff --git a/hdr/fcb.h b/hdr/fcb.h
index 252af47..ad2ae07 100644
--- a/hdr/fcb.h
+++ b/hdr/fcb.h
@@ -113,8 +113,8 @@ typedef struct _rfcb {
   BYTE renOldName[8];           /* Old Filename                 */
   BYTE renOldExtent[3];         /* Old File Extension           */
   BYTE renReserved1[5];
-  AR_MEMB(struct _rfcb, BYTE, renNewName, 8);           /* New Filename                 */
+  BYTE renNewName[8];           /* New Filename                 */
   BYTE renNewExtent[3];         /* New FileExtension            */
   BYTE renReserved2[9];
-} rfcb;
+} PACKED rfcb;
```
but now I get an FDPP compilation error what's the fix here, please?
~~~
clang++ -std=c++11 -iquote /clients/common/fdpp.git/fdpp/../hdr -Wall -c -fno-threadsafe-statics -fno-rtti -fpic -Wno-format-invalid-specifier -Wmissing-prototypes -ggdb3 -fdebug-macro -O0 -DI386 -DWITHFAT32 -I . -I /clients/common/fdpp.git/fdpp/../kernel/ -I /clients/common/fdpp.git/fdpp -DDATADIR=/usr/local/share/fdpp -DKRNL_NAME=fdppkrnl.sys -DCURDIR=/clients/common/fdpp.git/fdpp -o fcbfns.o fcbfns.cc
fcbfns.cc:557:20: error: no viable overloaded '='
      pFromPattern = lpRenameFcb->renNewName;
      ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
./farptr.hpp:139:7: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'BYTE [8]' to 'const FarPtr<const char>' for 1st argument
class FarPtr : public FarPtrBase<T>
      ^
1 error generated.
makefile:139: recipe for target 'fcbfns.o' failed
make[1]: *** [fcbfns.o] Error 1
make[1]: Leaving directory '/clients/common/fdpp.git/fdpp'
makefile:105: recipe for target 'all' failed
make: *** [all] Error 2
~~~

Previously the structure seen in gdb was
~~~
(gdb) p *(struct _rfcb *) &lowmem_base[(6588<<4)+286]
$19 = {renDriveID = 0 '\000', renOldName = "testa   ", renOldExtent = "bat", renReserved1 = "\000\000\000\000", renNewName = {<MembBase<char, &_rfcb::off_renNewName>> = {<No data fields>}, 
    sym = "testb   ", static len = 8}, renNewExtent = "bal", renReserved2 = "\000\000\000\000\000\000\000\000"}
~~~

**Comment by andrewbird** [comment]
Don't worry about this for now, I'll PACK the structure but not revert the AR_MEMB change. Looking at the following extension field I can see it's correct, so perhaps the AR_MEMB is correct and I've not found the real issue yet.

**Comment by stsp** [comment]
Just see its sizeof in gdb

**Comment by stsp** [comment]
It might be even possible to create the
generic macro for all types, and provide
it in .gdbinit.
What I meant however is whether the
packing changes sizeof. If so - its likely
needed.

**Comment by andrewbird** [comment]
Sure I'll check that later, it might not be required, all fields are bytes/byte arrays but they are odd sizes so I don't know if gcc pads for faster access alignment.
I think I found the problem, but it's so awful I don't really believe standard freedos could work. The structure is passed to FcbRename as an xfcb and processed as such into a rfcb, but in reality it's already an rfcb.
Anyway more fun later :smile:

**Comment by stsp** [comment]
So it doesn't look like you have returned
victorious from that battle? :)

**Comment by andrewbird** [comment]
I've been away from home, back now, so just getting back to it.

I fixed https://github.com/PerditionC/fdkernel/issues/16 though (variable shadowing)

**Comment by andrewbird** [comment]
Okay I think that the xfcb / rfcb mismatch probably doesn't matter as we are only interested in the first fields, which would explain why FreeDOS doesn't have a problem.
So moving on I step through `ConvertName83ToNameSZ()` which seems to do the right thing, but upon return the caller's buffer doesn't have the correct string in it. I notice that within `ConvertName83ToNameSZ()` the pointer destSZ is incremented to the end of the string. With your new C++ typing method is destSZ a copy of the pointer or is it messing up the callers pointer?

I made a copy of the destSZ pointer called odestSZ and can see just before return from `ConvertName83ToNameSZ()` that the buffer is correct
~~~
(gdb) p sdos(char, odestSZ)
$9 = 0xb00f200c "testa.bat"
~~~
But upon return to the caller I see
~~~
469	  ConvertName83ToNameSZ(MK_FAR_STR_SCP(pszBuffer), lpFcb->fcb_fname);
470	}
471	
472	UBYTE FcbDelete(__FAR(xfcb) lpXfcb)
473	{
474	  COUNT FcbDrive;
(gdb) p pszBuffer
$10 = (BYTE *) 0xb00f11ce "test\027\272\036\001\315!<"
~~~

Some [shenanigans](https://www.urbandictionary.com/define.php?term=shenanigans) occurring that I have no idea about - can you help?

**Comment by stsp** [comment]
If you return to the caller with `fin` or
alike, you may not yet see the changes.
Things are cached a lot.
If you step in gdb a few lines below, the
FAR emulator should update the cache
by that time, and hopefully you'll see what
you want. If not - a bug.

**Comment by andrewbird** [comment]
Firstly I find this thoroughly confusing :smile:, but since we passed in a pointer to `ConvertName83ToNameSZ()` and after the `memcpy()` + some other writes I saw by dereferencing a copy (odestSZ) of that original pointer that the write had correctly occurred, how can after I stepped right back out to the caller, the target buffer only had a partial write to it? It seems like corruption after the return to me...

**Comment by stsp** [comment]
Who told you that `odestSZ` is the actual copy
of the _caller-passed_ pointer, rather than some
intermediate pointer that FAR emulator uses for
caching?

Please just check that my guess is correct,
that stepping a few lines down, brings the caches
in sync.

**Comment by stsp** [comment]
>>   With your new C++ typing method is destSZ a copy of the pointer or is it messing up the callers pointer?
> Neither.

That was a clue.
Its neither.
Far emulator can pass whatever it wants.
Later, on a caller side, it can do some checks,
and, for example, it can even discard the memcpy
completely, if the caller's pointer happens to
be marked as const, for example.
(to check that this is true, you'll also have to
cast-away constness, or compiler will also
complain)

**Comment by andrewbird** [comment]
> Who told you that odestSZ is the actual copy
of the caller-passed pointer, rather than some
intermediate pointer that FAR emulator uses for
caching?

No one, but since it was copied from the destSZ pointer which was written to and the changes were visible via odestSZ I figured they were at least looking at the same buffer.

I stepped on as far as I could even into the next function that used it but the SecPathName buffer never got updated with the full path. Eventually I ended up in a signal/trap loop I could never get out of.

**Comment by andrewbird** [comment]
I pushed the https://github.com/andrewbird/fdpp/tree/FcbRename-01 branch so if you want to test at least you'll get valid return status now.

**Comment by stsp** [comment]
> No one, but since it was copied from the destSZ pointer which was written to
> and the changes were visible via odestSZ I figured they were at least looking at the same buffer.

Why "same buffer" is equal to "caller's buffer"? :)

**Comment by andrewbird** [comment]
But some of the content of "same buffer" ends up in "callers buffer", just not all of it. in fact what does get into "callers buffer" is first 4 chars of an 8 char `memcpy()`, which just seems strange to me.

**Comment by stsp** [comment]
OK, that might exactly be a bug: far amulator
may not synchronize the caches properly.
I'll need to take a look.

**Comment by stsp** [comment]
```
diff --git a/fdpp/farobj.hpp b/fdpp/farobj.hpp
index 0a8a56a..baed2d0 100644
--- a/fdpp/farobj.hpp
+++ b/fdpp/farobj.hpp
@@ -171,6 +171,7 @@ public:
 })
 #define MK_FAR_SCP(o) FarPtr<decltype(o)>(FarObj<decltype(o)>(o).get_obj())
 #define MK_FAR_STR_SCP(o) FarPtr<_RC(o)>(FarObj<_R(o)>(o, strlen(o) + 1).get_obj())
+#define MK_FAR_SZ_SCP(o, sz) FarPtr<_RC(o)>(FarObj<_R(o)>(o, sz).get_obj())
 
 #define PTR_MEMB(t) NearPtr_DO<t>
 #define NEAR_PTR_DO(t) NearPtr_DO<t>
diff --git a/kernel/fcbfns.c b/kernel/fcbfns.c
index 43a7d63..be24e9c 100644
--- a/kernel/fcbfns.c
+++ b/kernel/fcbfns.c
@@ -466,7 +466,7 @@ STATIC void FcbNameInit(fcb FAR * lpFcb, BYTE * szBuffer, COUNT * pCurDrive)
     pszBuffer[1] = ':';
     pszBuffer += 2;
   }
-  ConvertName83ToNameSZ(MK_FAR_STR_SCP(pszBuffer), lpFcb->fcb_fname);
+  ConvertName83ToNameSZ(MK_FAR_SZ_SCP(pszBuffer, 12), lpFcb->fcb_fname);
 }
 
 UBYTE FcbDelete(xfcb FAR * lpXfcb)
~
```

Please try something like this.
I think far emulator was not able to find the buffer size.

**Comment by stsp** [comment]
So if we tell him 12, that should be fine for 8.3 filename.

**Comment by andrewbird** [comment]
I think it can be prefixed with drive letter and colon too.

**Comment by andrewbird** [comment]
I think you fixed that issue because in the log file I can see which at least shows the name is being converted from 8.3 to string. Unfortuately I now get a crash - see the log 
[test4.zip](https://github.com/stsp/fdpp/files/2485181/test4.zip)

~~~
MFS: is_msdos_device /clients/common/dosemu2.git/test-imagedir/dXXXXs/d//testa.bat
MFS: file exists as is                                                          
MFS: 'TESTA   '.'BAT' hlist=0                                                   
MFS: hlist_pop: 1 popping=0 PSP=6588                                            
~~~

**Comment by stsp** [comment]
I am not providing this as a fix.
But please see if we are on a right track.

**Comment by stsp** [comment]
Try larger size if you want.
Thats just an example.

**Comment by stsp** [comment]
Ah, sorry! You already tried, but mobile
phone...

**Comment by andrewbird** [comment]
That looks to have fixed the buffer copy issue
~~~
(gdb) break fcbfns.cc:469
Breakpoint 2 at 0xb784a060: file fcbfns.cc, line 469.
(gdb) cont
Continuing.
ERROR: fdpp booting, this is very experimental!

Thread 1 "dosemu.bin" hit Breakpoint 2, FcbNameInit (lpFcb=..., szBuffer=0xb00f11ce "\016\037\270", pCurDrive=0x806fd44e) at fcbfns.cc:469
469	  ConvertName83ToNameSZ(MK_FAR_SZ_SCP(pszBuffer, 14), lpFcb->fcb_fname);
(gdb) p pszBuffer
$1 = (BYTE *) 0xb00f11ce "\016\037\270"
(gdb) next
470	}
(gdb) p pszBuffer
$2 = (BYTE *) 0xb00f11ce "testa.bat"
(gdb) next
CommonFcbInit (lpExtFcb=..., pszBuffer=0xb00f11ce "testa.bat", pCurDrive=0x806fd44e) at fcbfns.cc:453
453	  return lpFcb;
(gdb) l
448	  sda_lpFcb = lpFcb = ExtFcbToFcb(lpExtFcb);
449	
450	  /* Build a traditional DOS file name                            */
451	  FcbNameInit(lpFcb, pszBuffer, pCurDrive);
452	  /* and return the fcb pointer                                   */
453	  return lpFcb;
454	}
455	
456	STATIC void FcbNameInit(__FAR(fcb) lpFcb, BYTE * szBuffer, COUNT * pCurDrive)
457	{
(gdb) next
454	}
(gdb) 
FcbRename (lpXfcb=...) at fcbfns.cc:525
525	  if (IsDevice(SecPathName))
(gdb) p SecPathName
$3 = {<MembBase<char, &__SecPathBuffer::off__SecPathName>> = {<No data fields>}, 
  sym = "testa.bat\000<\000t\005\272c\001\353\003\272J\001\264\t\315!\264L\000\000\200\000\354\006@7\037\026\032\067\037\026\376\377\274\031\000\001\274\031command.com\000/ /P /E:256\r\n", '\000' <repeats 52 times>, static len = 128}
~~~

**Comment by andrewbird** [comment]
Off to bed now, speak tomorrow, goodnight!

**Comment by stsp** [comment]
Bye, thanks for your work!
As you havent said anything else, I
assume nothing actually worked,
besides buffer in gdb. :)

**Comment by stsp** [comment]
Ah, I see you also mention the crash...
Mobile phone sucks. :)

**Comment by stsp** [comment]
OK, in this case `lookup_sym()` fails, which is a
more usual situation. I'll look what expression it was
not able to evaluate.

**Comment by stsp** [comment]
`const char FAR *pFromPattern = Dmatch.dm_name;`
This one. Which looks like a quite simple expression
to parse... Not sure what went wrong, yet.

**Comment by stsp** [comment]
```
@@ -545,7 +545,7 @@ UBYTE FcbRename(xfcb FAR * lpXfcb)
       BYTE loc_szBuffer[2 + FNAME_SIZE + 1 + FEXT_SIZE + 1];
       fcb LocalFcb;
       BYTE *pToName;
-      const char FAR *pFromPattern = Dmatch.dm_name;
+      const char FAR *pFromPattern = Dmatch_p->dm_name;
       int i;
       UBYTE mode = 0;
 
@@ -652,8 +652,8 @@ UBYTE FcbFindFirstNext(xfcb FAR * lpXfcb, BOOL First)
   /* Reconstrct the dirmatch structure from the fcb - doesn't hurt for first */
   Dmatch_ff.dm_drive = lpFcb->fcb_sftno;
 
-  fmemcpy(Dmatch_ff.dm_name_pat, lpFcb->fcb_fname, FNAME_SIZE + FEXT_SIZE);
-  DosUpFMem((BYTE FAR *) Dmatch_ff.dm_name_pat, FNAME_SIZE + FEXT_SIZE);
+  fmemcpy(Dmatch_ff_p->dm_name_pat, lpFcb->fcb_fname, FNAME_SIZE + FEXT_SIZE);
+  DosUpFMem((BYTE FAR *) Dmatch_ff_p->dm_name_pat, FNAME_SIZE + FEXT_SIZE);
 
   Dmatch_ff.dm_attr_srch = wAttr;
   Dmatch_ff.dm_entry = lpFcb->fcb_strtclst;
```

Please try this.
I think it will fix the crash, but I am not sure at
all that this will generate the correct code...

**Comment by stsp** [comment]
When supporting FAR is too difficult, I usually
was just converting the code to the near pointers.
But in this particular case looks like too much code
is involved, so the conversion will mean a big patch.
Not sure...

**Comment by andrewbird** [comment]
Crash is gone, rename process is getting further now, but still failing for some reason. From reading the Dosemu log it looks like source file processing is complete and the fault is in the target file processing. Thanks, I'll see what the next step is.

**Comment by stsp** [comment]
How about converting it to flat pointers?
I suppose this code has a lot of miscompile
potential, even if plugged with those small
hacks here and there.

**Comment by andrewbird** [comment]
Test results are same or better than FreeDOS 1.20
#### FDPP
~~~
Test PP-DOS-1.00 MFS FCB file rename simple ... ok
Test PP-DOS-1.00 MFS FCB file rename source missing ... ok
Test PP-DOS-1.00 MFS FCB file rename target exists ... ok
Test PP-DOS-1.00 MFS FCB file rename wildcard one ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard two ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard three ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard four ... FAIL
~~~
#### FreeDOS 1.20
~~~
Test FR-DOS-1.20 MFS FCB file rename simple ... ok
Test FR-DOS-1.20 MFS FCB file rename source missing ... FAIL
Test FR-DOS-1.20 MFS FCB file rename target exists ... FAIL
Test FR-DOS-1.20 MFS FCB file rename wildcard one ... FAIL
Test FR-DOS-1.20 MFS FCB file rename wildcard two ... FAIL
Test FR-DOS-1.20 MFS FCB file rename wildcard three ... FAIL
Test FR-DOS-1.20 MFS FCB file rename wildcard four ... FAIL
~~~

**Comment by andrewbird** [comment]
Oh yes, and FcbRename() works correctly without the rfcb structure being packed, so I didn't change it.

**Comment by andrewbird** [comment]
I'll move on to the FCB wildcard issues, but that will be later I have other stuff to do today.

Thanks for your help.
